Unity Major Version
OneSignal/OneSignal-Unity-SDK pull request #402
Opened 2021-11-11 00:22 UTC by adamschlesinger

2021-11-11 03:49 UTC, jkasten2 requested changes
Omit all .jar / .aar files from `OneSignalExample/Assets/Android/`, these will get download by EDM4U automatically.

Left initial feedback, will be following up with a full review. Left comments on TODOs to address so we don't overlook them.

> Reviewed 13 of 81 files at r1, 8 of 69 files at r2, 4 of 18 files at r4, 4 of 50 files at r5, 2 of 182 files at r6, 6 of 62 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-:-MoC5jHHAU0XGAowvID4:b-ps8le1)* status: 37 of 351 files reviewed, 13 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Editor/SetupSteps/InstallEdm4uStep.cs, line 75 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBpTbP0fkGu1_YqHK6:-MoBpTbP0fkGu1_YqHK7:b-i00fko) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/370febd00fc0c416198cdd806c62742cdc6abb64/com.onesignal.unity.android/Editor/SetupSteps/InstallEdm4uStep.cs#L75)):*
> ```Smalltalk
>     private const string _shouldFix2021Bug = "onesignal.installedm4u.shouldfix2021bug";
>     private const string _iosDLLDestPath   = "Assets/ExternalDependencyManager/Editor/Google.IOSResolver.dll";
>     private static readonly string _iosDLLSourcePath = $"Assets/ExternalDependencyManager/Editor/Google.IOSResolver_v{_edm4UVersion}.dll";
> ```

Nice clean up! I see EDM4U fixed this in [1.2.167](https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md#version-12167---oct-6-2021)
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 72 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBseUEDigg4FM95_eh:-MoBseUEDigg4FM95_ei:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L72)):*
> ```Smalltalk
>         public override Task<NotificationPermission> PromptForPushNotificationsWithUserResponse() {
>             // cancels immediately, iOS only
>             // todo - is cancellation the right solution?
> ```

Address TODO
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 95 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBskJ40YEnQQrMBnOp:-MoBskJ40YEnQQrMBnOq:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L95)):*
> ```Smalltalk
> 
>         public override void RemoveTriggers(params string[] keys)
>             => _sdkClass.CallStatic("removeTriggersForKeys", keys.ToList()); // todo - test me thoroughly
> ```

Address TODO
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 160 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBt8Zf-aUpU0A-n7Od:-MoBt8Zf-aUpU0A-n7Oe:b-xm33ra) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L160)):*
> ```Smalltalk
>             LogOutOptions options = LogOutOptions.Email | LogOutOptions.SMS | LogOutOptions.ExternalUserId
>         ) {
>             throw new System.NotImplementedException();
> ```

Needs implementation
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 164 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBtPziDlo7sdOcTM3K:-MoBtPziDlo7sdOcTM3L:bl7ahm3) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L164)):*
> ```Smalltalk
> 
>         public override void PromptLocation()
>             => SDKDebug.Log("PromptLocation invoked on Android, does nothing.");
> ```

This should call [`promptLocation`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3bcc63f8f34bf4892fe3e8b72e5b72209c68e1ce/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2696).

Prompting will only work if the app has correctly add the location permission to their `AndroidManifest.xml` as well.
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 5 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoByuhUEZggmMVHMf2r:-MoByuhUEZggmMVHMf2s:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L5)):*
> ```Smalltalk
> 
> /// <summary>
> /// todo
> ```

Address TODO
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 9 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBywBB7lipcejyVHfl:-MoBywBB7lipcejyVHfm:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L9)):*
> ```Smalltalk
> public sealed class GUILayoutScope : IDisposable {
>     /// <summary>
>     /// todo
> ```

Address TODO
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 19 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBywmI0HZiG8IAf-47:-MoBywmI0HZiG8IAf-48:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L19)):*
> ```Smalltalk
> 
>     /// <summary>
>     /// todo
> ```

Address TODO
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 29 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoByxeWDZUMLeeHB3n6:-MoByxeWDZUMLeeHB3n7:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L29)):*
> ```Smalltalk
>         
>     /// <summary>
>     /// todo
> ```

Address TODO
___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 35 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBz0S85o8Pb91JhACD:-MoBz0S85o8Pb91JhACE:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/OneSignal.cs#L35)):*
> ```Smalltalk
> namespace OneSignalSDK {
>     /// <summary>
>     /// todo - desc
> ```

Address TODO
___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 91 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoC4HiV52eFrimHJGiY:-MoC4HiV52eFrimHJGiZ:b-b0g7ps) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/OneSignal.cs#L91)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// When an push notification has been received
> ```

Should be "when a push"
___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 105 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoC5Cdc1u2xJucMPand:-MoC5Cdc1u2xJucMPane:bvnd2aa) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/OneSignal.cs#L105)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// todo
> ```

Address TODOs in `core/Runtime/OneSignal.cs`
___
*[com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, line 6 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBp02O-CaJ059JVUYj:-MoBp02O-CaJ059JVUYk:b-58nt5h) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml#L6)):*
> ```XML
>       <repository>https://repo.maven.apache.org/maven2</repository>
>     </repositories>
>     <androidPackage spec="com.onesignal:OneSignal:[4.0.0, 4.99.99[" />
> ```

Should lock to a  [...]

2021-11-11 08:22 UTC, jkasten2 requested changes
> Reviewed 37 of 81 files at r1, 14 of 69 files at r2, 6 of 17 files at r3, 1 of 18 files at r4, 5 of 50 files at r5, 3 of 62 files at r7.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 103 of 351 files reviewed, 17 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 66 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCOmxc1BB0dicZlqOJ:-MoCOmxc1BB0dicZlqOK:br00j27) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L66)):*
> ```Smalltalk
>             var context     = activity.Call<AndroidJavaObject>("getApplicationContext");
> 
>             _sdkClass.CallStatic("initWithContext", context);
> ```

We should provide an `Activity` instance instead of the application context. This is important as the OneSignal native SDK will think the app is in the background otherwise when it is not. Android doesn't have an API to know if the app is in the foreground currently based on a context alone, it only provides a ActivityLifecycleListener but it only fires when there is a change.
___
*[com.onesignal.unity.core/Runtime/Models/Notification.cs, line 48 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCJAE19fy8Kmc7HRtp:-MoCJAE19fy8Kmc7HRtq:b3rx4oi) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Models/Notification.cs#L48)):*
> ```Smalltalk
>     /// todo - struct?
>     /// </summary>
>     [Serializable] public sealed class Notification {
> ```

This looks like the old format for the OneSignal Notification class. See the new properties defined in the native SDKs.
* https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.6.2/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotification.java#L51
* https://github.com/OneSignal/OneSignal-iOS-SDK/blob/3.8.1/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L68
___
*[com.onesignal.unity.core/Runtime/Models/NotificationPayload.cs, line 36 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCLfL9AST4NZ3f02aC:-MoCLfLAEUFVE5gybtcz:b-2w47e5) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Models/NotificationPayload.cs#L36)):*
> ```Smalltalk
>     /// todo - struct?
>     /// </summary>
>     [Serializable] public sealed class NotificationPayload {
> ```

The payload class was removed in the latest versions, since all these properties now live on the OSNotification class instead.
___
*[com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab, line 1 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCNxHjB-ngDnBMtzvo:-MoCNxHk7AeYakIoFwVs:b3vv37v) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab#L1)):*
> ```
> %YAML 1.1
> ```

Why do we have a prefab for OneSignalController?


<!-- Sent from Reviewable.io -->

2021-11-12 19:19 UTC, jkasten2 requested changes
> Reviewed 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 103 of 351 files reviewed, 18 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, line 132 at r8](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoK_V3a8j_LPfm-vvDG:-MoK_V3a8j_LPfm-vvDH:b-6lag41) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06be82a04bbaac36c50d2695c1afdb63a9bbb259/com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs#L132)):*
> ```Smalltalk
>         }
> 
>         private sealed class OSRemoteNotificationReceivedHandler : OneSignalAndroidJavaProxy {
> ```

Remove this class, this was only designed to be used from the NSE.
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, line 146 at r8](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKYzx89Q67J67qHujb:-MoKYzx89Q67J67qHujc:b482dks) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06be82a04bbaac36c50d2695c1afdb63a9bbb259/com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs#L146)):*
> ```Smalltalk
>             /// <param name="notificationReceivedEvent">OSNotificationReceivedEvent</param>
>             [Preserve] public void notificationWillShowInForeground(AndroidJavaObject notificationReceivedEvent)
>                 => _instance.NotificationReceived?.Invoke(_notificationFromEventJavaObject(notificationReceivedEvent));
> ```

It is expected that `notificationReceivedEvent.complete` is called once the app developer can determine if they want to display a notification or not. The API to developers does not reflect that.


<!-- Sent from Reviewable.io -->

2021-11-12 19:24 UTC, adamschlesinger reviewed
If we're going to do this I'd recommend we switch to import dependencies via gradle instead of via EDM4U. 

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-:-MoKNDYWEZRg-Crpoh-k:boqphss)* status: 102 of 351 files reviewed, 18 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 66 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCOmxc1BB0dicZlqOJ:-MoKOEcj9eVqaHZwFeh9:b-kovub6) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L66)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

We should provide an `Activity` instance instead of the application context. This is important as the OneSignal native SDK will think the app is in the background otherwise when it is not. Android doesn't have an API to know if the app is in the foreground currently based on a context alone, it only provides a ActivityLifecycleListener but it only fires when there is a change.
</blockquote></details>

Shouldn't the init method require this in that case? At the least we should probably encourage this in the inline docs. Regardless, updated.
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 72 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBseUEDigg4FM95_eh:-MoK_-KR8s2H0_kYlxuX:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L72)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODO
</blockquote></details>

Done.
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 164 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBtPziDlo7sdOcTM3K:-MoK_XPf4RwDFO5Xmqmc:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L164)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This should call [`promptLocation`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3bcc63f8f34bf4892fe3e8b72e5b72209c68e1ce/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2696).

Prompting will only work if the app has correctly add the location permission to their `AndroidManifest.xml` as well.
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab, line 1 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCNxHjB-ngDnBMtzvo:-MoK_mee2288rOKz7Pkd:b-56uejf) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab#L1)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Why do we have a prefab for OneSignalController?
</blockquote></details>

Codeless init. They can drag this MB into their opening scene and it will start OneSignal without them adding any code to the app.
___
*[com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml, line 6 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBp02O-CaJ059JVUYj:-MoKMrT84WyFDVXqpq8h:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Editor/OneSignalAndroidDependencies.xml#L6)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Should lock to a specific version. Recommend the latest OneSignal-Android-SDK which is `4.6.2`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 20:20 UTC, jkasten2 requested changes
Referring to just omitting them from git, they shouldn't be checked in.

> Reviewed 8 of 69 files at r2, 13 of 50 files at r5, 2 of 62 files at r7, 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-:-MoKnePy47tmaPTeg_Bp:b-ahutcc)* status: 127 of 351 files reviewed, 21 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.ios/Editor/BuildPostProcessor.cs, line 78 at r8](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKjwaBAtd3RatqIYsn:-MoKjwaBAtd3RatqIYso:b-yw7hhh) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06be82a04bbaac36c50d2695c1afdb63a9bbb259/com.onesignal.unity.ios/Editor/BuildPostProcessor.cs#L78)):*
> ```Smalltalk
>         private static readonly string PluginFilesPath = Path.Combine("Packages", PluginLibrariesPath);
> 
>         private static readonly string[] RequiredFrameworks = {
> ```

Since this now adds OneSignal via Cocoapods these are automatically added by it so we can remove the framework definitions here.
___
*[com.onesignal.unity.ios/Editor/BuildPostProcessor.cs, line 302 at r8](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKkuz56q1jFNFjbvEt:-MoKkuz56q1jFNFjbvEu:byzpp5j) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06be82a04bbaac36c50d2695c1afdb63a9bbb259/com.onesignal.unity.ios/Editor/BuildPostProcessor.cs#L302)):*
> ```Smalltalk
>             File.WriteAllText(podfilePath, podfile);
>             
>             // todo - detect if cocoapods is installed
> ```

Address TODO
___
*[com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml, line 3 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKl5tN627W4Iz4bmS_:-MoKl5tN627W4Iz4bmSa:b-o5iclf) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml#L3)):*
> ```XML
> <dependencies>
>     <iosPods>
>         <iosPod name="OneSignalXCFramework" version="~> 3.8.1"  addToAllTargets="true" />
> ```

Instead of adding to all targets should it only add it to the main target? We do want OneSignal to also be added to the NSE target, however this `addToAllTargets` doesn't work with that since we have a post build script that adds the NSE target at end.


<!-- Sent from Reviewable.io -->

2021-11-12 20:27 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 120 of 351 files reviewed, 21 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, line 146 at r8](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKYzx89Q67J67qHujb:-MoKpDNH-d1rtFW4dB4M:b-pakp0l) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06be82a04bbaac36c50d2695c1afdb63a9bbb259/com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs#L146)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

It is expected that `notificationReceivedEvent.complete` is called once the app developer can determine if they want to display a notification or not. The API to developers does not reflect that.
</blockquote></details>

Updated to require a boolean response of true or false which is passed to the correct functionality on the native side.


<!-- Sent from Reviewable.io -->

2021-11-12 20:29 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 120 of 351 files reviewed, 21 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.ios/Editor/BuildPostProcessor.cs, line 78 at r8](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKjwaBAtd3RatqIYsn:-MoKpl1J3u_tRBDshRVS:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06be82a04bbaac36c50d2695c1afdb63a9bbb259/com.onesignal.unity.ios/Editor/BuildPostProcessor.cs#L78)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Since this now adds OneSignal via Cocoapods these are automatically added by it so we can remove the framework definitions here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 21:55 UTC, jkasten2 requested changes
> Reviewed 5 of 69 files at r2, 3 of 17 files at r3, 5 of 18 files at r4, 17 of 50 files at r5, 143 of 182 files at r6, 49 of 62 files at r7, 1 of 1 files at r9, 10 of 10 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: all files reviewed, 21 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 66 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCOmxc1BB0dicZlqOJ:-MoKpGvR4eLHhTLyuPI2:bsznmke) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L66)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

Shouldn't the init method require this in that case? At the least we should probably encourage this in the inline docs. Regardless, updated.
</blockquote></details>

Actually it is preferred to initialize OneSignal before any `Activities` are shown, which would be the `Application.onCreate`, in that case it will be the an application `Context`. This why you don't have to add OneSignal initialize code to every `Activity` in the app.

However this is not possible in Unity so using the `Activity` is the best we can do.
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, line 149 at r12](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL6m0-E_HCEE0wnAYQ:-MoL6m0-E_HCEE0wnAYR:b8ur5ru) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/65d78bbd598b103a55c30991e029577018c172cd/com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs#L149)):*
> ```Smalltalk
>                 
>                 if (_instance.NotificationReceived == null || _instance.NotificationReceived(notifJO.ToSerializable<Notification>()))
>                     notificationReceivedEvent.Call("complete", notifJO);
> ```

`complete` needs to be called developer when the developer returns `false` from `NotificationReceived` too, it just needs to be done with a `null` notification instance so the notification is not displayed. Otherwise the native SDK will wait 25 seconds and display the notification anyway.

Also on this API, not sure what thread this callback fires on, should we provide a similar complete method to allow taking more time on a background thread?
___
*[com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab, line 1 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCNxHjB-ngDnBMtzvo:-MoL82ED3jotGHXwsvEv:b4c9lyr) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab#L1)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

Codeless init. They can drag this MB into their opening scene and it will start OneSignal without them adding any code to the app.
</blockquote></details>

:thumbsup: 
___
*[com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm, line 172 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKo9TXB-pa4pNrYuOn:-MoKo9TXB-pa4pNrYuOo:bpk4nly) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm#L172)):*
> ```XML
>         [OneSignal setNotificationWillShowInForegroundHandler:^(OSNotification *notification, OSNotificationDisplayResponse completion) {
>             NSString *stringResponse = [notification stringify];
>             callback([stringResponse UTF8String]);
> ```

Same apps to iOS as my comment on iOS about `notificationWillShowInForegroundHandler`, we need an API for the developer to call the `completion` / `complete` callback / handler.
___
*[com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm, line 174 at r12](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL8LMS1ZEyAj3fzIET:-MoL8LMS1ZEyAj3fzIEU:b-p35gu4) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/65d78bbd598b103a55c30991e029577018c172cd/com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm#L174)):*
> ```XML
>         [OneSignal setNotificationWillShowInForegroundHandler:^(OSNotification *notification, OSNotificationDisplayResponse completion) {
>             NSString *stringResponse = [notification stringify];
>             if (callback([stringResponse UTF8String]))
> ```

Need to call `completion(nil)` when callback is `false` to omit displaying the notification.
___
*[OneSignalExample/Assets/Plugins/Android/gradleTemplate.properties, line 7 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKyyk1DuA_0jxaJufS:-MoKyyk1DuA_0jxaJufT:bl5ixja) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/OneSignalExample/Assets/Plugins/Android/gradleTemplate.properties#L7)):*
> ```INI
> # Android Resolver Properties Start
> android.useAndroidX=true
> android.enableJetifier=true
> ```

We don't have to enable Jetifier any more, since OneSignal and all it's dependencies no longer use the Android Support Libraries and have been switched over to AndroidX.
(I think this gets created from EDM4U based on the project settings, so this is most likely just a change in our setup guide)
___
*[OneSignalExample/Assets/Plugins/Android/LauncherManifest.xml.DISABLED, line 3 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL4b1188H_Hl0zHb3s:-MoL4b1188H_Hl0zHb3t:b-80k576) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/OneSignalExample/Assets/Plugins/Android/LauncherManifest.xml.DISABLED#L3)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <!-- GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN-->
> <manifest
> ```

Delete this file
___
*[OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, line 3 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL4yew1PSQhm0LZ9Mr:-MoL4yew1PSQhm0LZ9Ms:b-gvf1kk) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml#L3)):*
> ```XML
> <dependencies>
>   <packages>
>     <package>com.onesignal:OneSignal:[4.0.0, 4.99.99[</package>
> ```

Wrong version range, I think this is a generated lock file and needs to be committed with the latest changes.
___
*[OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle.DISABLED, line 4 at r12](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL4gAkEnPU1cKnuE_p:-MoL4gAkEnPU1cKnuE_q:b1r6u5r) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/65d78bbd598b103a55c30991e029577018c172cd/OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle.DISABLED#L4)):*
> ```
> 
> // Android Resolver Repos Start
> ([rootProject] + (rootProject.subprojects as List)).each { project ->
> ```

Delete this file instead of disabling it.


<!-- Sent from Reviewable.io -->

2021-11-12 22:47 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 344 of 351 files reviewed, 21 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Editor/SetupSteps/InstallEdm4uStep.cs, line 75 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBpTbP0fkGu1_YqHK6:-MoLEQm04Rf8f1DoxiQ0:b-eg0xk) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/370febd00fc0c416198cdd806c62742cdc6abb64/com.onesignal.unity.android/Editor/SetupSteps/InstallEdm4uStep.cs#L75)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Nice clean up! I see EDM4U fixed this in [1.2.167](https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md#version-12167---oct-6-2021)
</blockquote></details>

I think there must have been an issue with the diff? This code was already cleaned out with an update to 1.2.167. 
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, line 132 at r8](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoK_V3a8j_LPfm-vvDG:-MoLIKxW26Fb78ixgy2c:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/06be82a04bbaac36c50d2695c1afdb63a9bbb259/com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs#L132)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove this class, this was only designed to be used from the NSE.
</blockquote></details>

Done.
___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs, line 149 at r12](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL6m0-E_HCEE0wnAYQ:-MoLJ6XOBW8dH451hkvN:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/65d78bbd598b103a55c30991e029577018c172cd/com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs#L149)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

`complete` needs to be called developer when the developer returns `false` from `NotificationReceived` too, it just needs to be done with a `null` notification instance so the notification is not displayed. Otherwise the native SDK will wait 25 seconds and display the notification anyway.

Also on this API, not sure what thread this callback fires on, should we provide a similar complete method to allow taking more time on a background thread?
</blockquote></details>

Done.
___
*[com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm, line 172 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKo9TXB-pa4pNrYuOn:-MoLJpTkALKQf--HnQOb:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm#L172)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Same apps to iOS as my comment on iOS about `notificationWillShowInForegroundHandler`, we need an API for the developer to call the `completion` / `complete` callback / handler.
</blockquote></details>

Done.
___
*[com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm, line 174 at r12](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL8LMS1ZEyAj3fzIET:-MoLJq2M4gKzL4CowhiF:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/65d78bbd598b103a55c30991e029577018c172cd/com.onesignal.unity.ios/Runtime/Plugins/iOS/OneSignalUnityBridge.mm#L174)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Need to call `completion(nil)` when callback is `false` to omit displaying the notification.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-15 21:06 UTC, jkasten2 requested changes
> Reviewed 5 of 6 files at r13, 2 of 2 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 176 of 357 files reviewed, 12 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 57 at r15](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-Mo_AyX2CVEhVePErrz0:-Mo_AyX2CVEhVePErrz1:b-n08prg) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/eb8491bef3b191a30037fae0e568a7ba41e5dd2d/com.onesignal.unity.core/Runtime/OneSignal.cs#L57)):*
> ```Smalltalk
>         /// <param name="notification">Details of the notification to be shown</param>
>         /// <returns>True if the notification should be displayed</returns>
>         public delegate bool NotificationReceivedDelegate(Notification notification);
> ```

What do you think about renaming this to `NotificationWillShowInForegroundDelegate`? Doing so will match the naming we have for native and our other wrapper SDKs.

Background on the naming. This very verbose name was picked over "NotificationReceived" as it doesn't communicate the foreground caveat, nor the timing and the control it has over the notification display.
* "Foreground" in the name to make it clear this never fires in the background. (A received event can't fire reliably for iOS, inefficient for Android [if it is even possible for Unity])
* "WillShow" make it clear this fires before the notification is shown. Method signature indicates that you have control over this.

2nd change, method signature. What do you think about changing the return type from `bool` to `Notification`? This will allow the OneSignal SDK to provide the option to modify the notification before displaying in the future. A `bool` signature locks us out of this option.


<!-- Sent from Reviewable.io -->

2021-11-15 21:12 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 170 of 357 files reviewed, 12 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 66 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCOmxc1BB0dicZlqOJ:-MoZNeWS12a2xCYnVhhl:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L66)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Actually it is preferred to initialize OneSignal before any `Activities` are shown, which would be the `Application.onCreate`, in that case it will be the an application `Context`. This why you don't have to add OneSignal initialize code to every `Activity` in the app.

However this is not possible in Unity so using the `Activity` is the best we can do.
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 35 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBz0S85o8Pb91JhACD:-Mo_Q3_t-2COcr5Mw9sC:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/OneSignal.cs#L35)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODO
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 91 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoC4HiV52eFrimHJGiY:-Mo_QFAK-V1ndx2m0Rzd:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/OneSignal.cs#L91)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Should be "when a push"
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Runtime/Models/Notification.cs, line 48 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCJAE19fy8Kmc7HRtp:-Mo_QIMg23lcyWrHG_Bl:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Models/Notification.cs#L48)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This looks like the old format for the OneSignal Notification class. See the new properties defined in the native SDKs.
* https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.6.2/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotification.java#L51
* https://github.com/OneSignal/OneSignal-iOS-SDK/blob/3.8.1/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L68
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab, line 1 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCNxHjB-ngDnBMtzvo:-Mo_QJTf3l7zpbVSN_RJ:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Prefabs/OneSignalController.prefab#L1)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.
___
*[OneSignalExample/Assets/Plugins/Android/gradleTemplate.properties, line 7 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKyyk1DuA_0jxaJufS:-Mo_QPzW1n4fW0rgZLI5:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/OneSignalExample/Assets/Plugins/Android/gradleTemplate.properties#L7)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

We don't have to enable Jetifier any more, since OneSignal and all it's dependencies no longer use the Android Support Libraries and have been switched over to AndroidX.
(I think this gets created from EDM4U based on the project settings, so this is most likely just a change in our setup guide)
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 5 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoByuhUEZggmMVHMf2r:-Mo_Pwvg-dv82nPTkcUt:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L5)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODO
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 9 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBywBB7lipcejyVHfl:-Mo_Q-YE74cHiR_Lg_qT:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L9)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODO
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 19 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBywmI0HZiG8IAf-47:-Mo_Q1L98hXx4QK1UN9Z:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L19)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODO
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs, line 29 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoByxeWDZUMLeeHB3n6:-Mo_Q26lA68brDvoI8NX:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Editor/Utilities/GUILayoutScope.cs#L29)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODO
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Runtime/Models/NotificationPayload.cs, line 36 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoCLfL9AST4NZ3f02aC:-Mo_RUJm0RJrgT3Q0wH9:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/Models/NotificationPayload.cs#L36)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

The payload class was removed in the latest versions, since all these properties now live on the OSNotification class instead.
</blockquote></details>

Done.
___
*[OneSignalExample/Assets/Plugins/Android/LauncherManifest.xml.DISABLED, line 3 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL4b1188H_Hl0zHb3s:-Mo_QimW7H5vq-xwrlke:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/OneSignalExample/Assets/Plugins/Android/LauncherManifest.xml.DISABLED#L3)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Delete this file
</blockquote></details>

Done.
___
*[OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle.DISABLED, line 4 at r12](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL4gAkEnPU1cKnuE_p:-Mo_Qk60Dxid3bMhhRk3:b-xqdiyt) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/65d78bbd598b103a55c30991e029577018c172cd/OneSignalExample/Assets/Plugins/Android/mainTemplate.gradle.DISABLED#L4)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Delete this file instead of disabling it.
</blockquote></details>

Changed project to use gradle instead of i [...]

2021-11-15 21:14 UTC, adamschlesinger reviewed
Done. Changed to gradle for builds instead of imported AARs.

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-:-Mo_RbFp0jaGFlHNAXI6:b-wnz2sv)* status: 170 of 357 files reviewed, 12 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml, line 3 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoL4yew1PSQhm0LZ9Mr:-Mo_RZyQ79hgrQ3THJ_4:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/OneSignalExample/ProjectSettings/AndroidResolverDependencies.xml#L3)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Wrong version range, I think this is a generated lock file and needs to be committed with the latest changes.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-15 21:26 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 170 of 357 files reviewed, 12 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 105 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoC5Cdc1u2xJucMPand:-Mo_UY8vAX3acQk6Fc6M:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.core/Runtime/OneSignal.cs#L105)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODOs in `core/Runtime/OneSignal.cs`
</blockquote></details>

Done.
___
*[com.onesignal.unity.core/Runtime/OneSignal.cs, line 57 at r15](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-Mo_AyX2CVEhVePErrz0:-Mo_S33V0spnN5ppp9sV:bfejjcz) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/eb8491bef3b191a30037fae0e568a7ba41e5dd2d/com.onesignal.unity.core/Runtime/OneSignal.cs#L57)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

What do you think about renaming this to `NotificationWillShowInForegroundDelegate`? Doing so will match the naming we have for native and our other wrapper SDKs.

Background on the naming. This very verbose name was picked over "NotificationReceived" as it doesn't communicate the foreground caveat, nor the timing and the control it has over the notification display.
* "Foreground" in the name to make it clear this never fires in the background. (A received event can't fire reliably for iOS, inefficient for Android [if it is even possible for Unity])
* "WillShow" make it clear this fires before the notification is shown. Method signature indicates that you have control over this.

2nd change, method signature. What do you think about changing the return type from `bool` to `Notification`? This will allow the OneSignal SDK to provide the option to modify the notification before displaying in the future. A `bool` signature locks us out of this option.
</blockquote></details>

`NotificationWillShow` would be a good option. I think it's implied to be in the foreground since it occurs during runtime.

As far as the signature I'm open to that but I'd be concerned about confusing devs that they can make those changes (until the functionality exists). Arguably, we could introduce that in a update "soon".


<!-- Sent from Reviewable.io -->

2021-11-15 22:49 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 163 of 360 files reviewed, 12 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 160 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBt8Zf-aUpU0A-n7Od:-Mo_mJOAABzynTbay3ER:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L160)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Needs implementation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-15 22:53 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: 163 of 360 files reviewed, 12 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.android/Runtime/OneSignalAndroid.cs, line 95 at r7](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoBskJ40YEnQQrMBnOp:-Mo_nSu1CiDB3OHWJN_v:b-896fix) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/bef985f6b91b5740b004349666f9b2d1ad019a3d/com.onesignal.unity.android/Runtime/OneSignalAndroid.cs#L95)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Address TODO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-17 00:02 UTC, jkasten2 reviewed
> Reviewed 162 of 173 files at r16, 12 of 16 files at r17, 5 of 7 files at r19, 1 of 1 files at r24, 5 of 8 files at r25, 12 of 12 files at r27, 1 of 1 files at r28, 2 of 2 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: all files reviewed, 3 unresolved discussions (waiting on @adamschlesinger, @emawby, @Jeasmine, @jkasten2, @jmadler, @nan-li, @rgomezp, and @tanaynigam)



<!-- Sent from Reviewable.io -->

2021-11-17 00:04 UTC, jkasten2 approved these changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby, @Jeasmine, @jmadler, @nan-li, @rgomezp, and @tanaynigam)

___
*[com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml, line 3 at r9](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402#-MoKl5tN627W4Iz4bmS_:-MofCNWwCj3F-8xoHJK_:b-2ccgra) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/e3cca8ed4cbb5ec9b0a16eed35d7cad38750de34/com.onesignal.unity.ios/Editor/OneSignalIOSDependencies.xml#L3)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Instead of adding to all targets should it only add it to the main target? We do want OneSignal to also be added to the NSE target, however this `addToAllTargets` doesn't work with that since we have a post build script that adds the NSE target at end.
</blockquote></details>

Based on your other changes it looks like we do want to keep this now.


<!-- Sent from Reviewable.io -->

2021-11-17 01:01 UTC, jkasten2 approved these changes
> Reviewed 7 of 7 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby, @Jeasmine, @jmadler, @nan-li, @rgomezp, and @tanaynigam)



<!-- Sent from Reviewable.io -->

2021-11-17 01:12 UTC, merged

2021-11-19 21:18 UTC, jkasten2 commented on com.onesignal.unity.core/Runtime/Models/Notification.cs
> +    [Serializable] public sealed class Notification {
@adamschlesinger This is missing `additionalData`