[FEATURE] Check EDM4U Version
OneSignal/OneSignal-Unity-SDK pull request #496
Opened 2022-05-03 00:15 UTC by shepherd-l

### Changed
- `InstallEdm4uStep` checks and imports version 1.2.169 and above of EDM4U

2022-05-03 16:08 UTC, adamschlesinger requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @adamschlesinger and @shepherd-l)

___
*[`com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs` line 71 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496#-N19ctsTEFRYy5stODBx:-N19ctsTEFRYy5stODBy:bopsu5i) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/46d941c547bd296893d2a7321f03f3f47f7321a5/com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs#L71)):*
> ```Smalltalk
> 
>             if (files.Length == 0) {
>                 SDKDebug.Warn("external-dependency-manager_version-{VERSION_NUMBER}_manifest.txt file does not exist.");
> ```

With this check we're primarily just trying to find if the folder is in an unexpected state. Let's have this check for `if length != 1` and change the warning to `EDM4U version number could not be determined. `
___
*[`OneSignalExample/Assets/OneSignal/CHANGELOG.md` line 11 at r1](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496#-N19e2eN3QfEGxu7CsmV:-N19e2eN3QfEGxu7CsmW:b-sg3b4p) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/46d941c547bd296893d2a7321f03f3f47f7321a5/OneSignalExample/Assets/OneSignal/CHANGELOG.md#L11)):*
> ```Markdown
> - Updated included Android SDK to [4.7.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.1)
> - Explicitly check for a diff and handle overwrites for the `AndroidManifest.xml` between the project's and package's `OneSignalConfig.plugin`
> - `InstallEdm4uStep` checks and imports version 1.2.169 and above of EDM4U
> ```

I'd like to see this as: `InstallEDM4UStep` checks for version number to determine if step is completed.


<!-- Sent from Reviewable.io -->

2022-05-03 22:31 UTC, jkasten2 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496)* status: all files reviewed, 1 unresolved discussion (waiting on @shepherd-l)

___
*[`com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs` line 75 at r2](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496#-N1B1fiT1obgqwKr-fFc:-N1B1fiT1obgqwKr-fFd:b-3w3365) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/dfac13f4eca27bfa7a1b5966d2be552225183a35/com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs#L75)):*
> ```Smalltalk
>             }
> 
>             var file = files[0];
> ```

Would there ever be more than one file? If not then can we add a comment noting that here?
If there can be we should ether clean up the old version files.


<!-- Sent from Reviewable.io -->

2022-05-04 15:29 UTC, shepherd-l commented
*[`com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs` line 75 at r2](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496#-N1B1fiT1obgqwKr-fFc:-N1Efnqh7mDFoJ2j42n3:bkh4bs8) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/dfac13f4eca27bfa7a1b5966d2be552225183a35/com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs#L75)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Would there ever be more than one file? If not then can we add a comment noting that here?
If there can be we should ether clean up the old version files.
</blockquote></details>

There can be more than one file but we would be unable to tell which file name has the current version number.

After checking that the length of the file array is equal to one, there should be only one file. Adding a comment for clarification sounds good to me. For noting that, did you mean that the comment should say that the array has one file?


<!-- Sent from Reviewable.io -->

2022-05-04 18:52 UTC, jkasten2 approved these changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shepherd-l)

___
*[`com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs` line 75 at r2](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496#-N1B1fiT1obgqwKr-fFc:-N1FPFGNAHvoV7xTwpx6:bqlx81d) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/dfac13f4eca27bfa7a1b5966d2be552225183a35/com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs#L75)):*
<details><summary><i>Previously, shepherd-l (Shepherd) wrote…</i></summary><blockquote>

There can be more than one file but we would be unable to tell which file name has the current version number.

After checking that the length of the file array is equal to one, there should be only one file. Adding a comment for clarification sounds good to me. For noting that, did you mean that the comment should say that the array has one file?
</blockquote></details>

Sorry I overlooked the `if (files.Length != 1) {` check above. The reason behind the code is clear enough so we can omit a comment.


<!-- Sent from Reviewable.io -->

2022-05-04 21:00 UTC, adamschlesinger approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shepherd-l)

___
*[`com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs` line 75 at r2](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/496#-N1B1fiT1obgqwKr-fFc:-N1B4eWv5K4jU0-pGdd_:b-4xyd4t) ([raw file](https://github.com/onesignal/onesignal-unity-sdk/blob/dfac13f4eca27bfa7a1b5966d2be552225183a35/com.onesignal.unity.core/Editor/SetupSteps/InstallEdm4uStep.cs#L75)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Would there ever be more than one file? If not then can we add a comment noting that here?
If there can be we should ether clean up the old version files.
</blockquote></details>

There shouldn't be more than one hence why we check above and log a warning if there is.


<!-- Sent from Reviewable.io -->

2022-05-04 21:02 UTC, merged