[User Model] Pascal case model properties
OneSignal/OneSignal-Unity-SDK pull request #590
Opened 2023-03-10 12:22 UTC by shepherd-l

# Description
## One Line Summary
Renamed model properties to Pascal Case.

## Details

### Motivation
Updates our code base style to follow C# coding conventions

# Testing
## Manual testing
Tested sending and opening a notification, displaying and dismissing an in app message, and opting in and out of the push subscription. App build with Android Studio 2022.1.1 and Xcode 14.2 with the OneSignal example app on a Pixel 4 simulator with Android 12 and on an iPhone 12 on iOS 15.5.

# Affected code checklist
   - [x] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [x] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

2023-03-23 14:47 UTC, brismithers commented on com.onesignal.unity.core/Runtime/Notifications/Models/INotification.cs
> +        public string Image { get; }
interface should not have `public`

2023-03-23 14:47 UTC, brismithers commented on com.onesignal.unity.core/Runtime/Notifications/Models/INotification.cs
> +        Dictionary<string, object> AdditionalData { get; }
you might be able to make this `IDictionary<string, object>` to provide a little more abstraction

2023-03-23 14:47 UTC, brismithers commented on com.onesignal.unity.core/Runtime/Notifications/Models/INotification.cs
> +        Dictionary<string, object> Attachments { get; }
you might be able to make this IDictionary<string, object> to provide a little more abstraction

2023-05-02 16:29 UTC, jkasten2 requested changes
Feedback is around missing the latest spec changes

2023-05-02 16:29 UTC, jkasten2 commented on com.onesignal.unity.core/Runtime/Notifications/Models/INotificationAction.cs
> +    public enum ActionType {
ActionType has been removed in the latest spec

2023-05-02 16:29 UTC, jkasten2 commented on com.onesignal.unity.core/Runtime/Notifications/Models/INotificationClickedResult.cs
> +    public interface INotificationClickedResult {
The latest spec has this as an event, the result is contained in the event instead.

2023-05-02 16:29 UTC, jkasten2 commented on com.onesignal.unity.core/Runtime/OneSignal.cs
> +        public abstract Task<bool> EnterLiveActivityAsync(string activityId, string token);
The latest spec moved these into there own "namespace" of `LiveActivities`

2023-05-10 14:48 UTC, merged