[Fix] iOS bitcode build error
OneSignal/OneSignal-Unity-SDK pull request #645
Opened 2023-10-03 05:15 UTC by shepherd-l

# Description
## One Line Summary
Fixes iOS "does not contain bitcode" build error.

## Details

### Motivation
Prevent iOS builds from failing with default "Enable Bitcode" value and document setting "Enable Bitcode" to "No".

# Testing
## Manual testing
Tested OneSignal initialization, app build with Unity 2022.3.10f1 of the OneSignal example app on a physical iPhone 12 with iOS 15.5.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

2023-10-03 17:29 UTC, jkasten2 requested changes

2023-10-03 17:29 UTC, jkasten2 commented on README.md
> +   **App Groups** should now be provisioned for you going forward for your iOS bundle id, even on clean builds.
Shouldn't this stay as step 6?

2023-10-03 17:29 UTC, jkasten2 commented on README.md
> +6. Make sure all **Targets** have **Enable Bitcode** set to **No** in **Build Settings**.
Per note above, this should be step 7.

2023-10-03 17:29 UTC, jkasten2 commented on com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
> +            // Unity Tests
This method's logic is mostly declarative vs imperative. Can we make a new method call something like `DisableBitcode()`?

2023-10-03 17:29 UTC, jkasten2 commented on com.onesignal.unity.ios/Editor/BuildPostProcessor.cs
> +            _project.SetBuildProperty(targetGuid, "ENABLE_BITCODE", "NO");
This method is named `AddProjectCapabilities` which shouldn't touch something unrelated like bitcode. I recommend moving this to the new `DisableBitcode()` method I suggested above.

2023-10-03 17:29 UTC, jkasten2 commented on OneSignalExample/Assets/OneSignal/CHANGELOG.md
> +- iOS bitcode build error
I would state we are disabling bitcode to avoid a build error.

2023-10-04 19:19 UTC, emawby approved these changes

2023-10-04 19:50 UTC, merged